<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKC6tVlI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKC6tVlI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKC6tVlI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKC6tVlI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKC6tVlI\App_KernelDevDebugContainer([
    'container.build_hash' => 'KC6tVlI',
    'container.build_id' => 'c242ee91',
    'container.build_time' => 1775482420,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKC6tVlI');
