<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1eLJxhw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1eLJxhw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1eLJxhw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1eLJxhw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1eLJxhw\App_KernelDevDebugContainer([
    'container.build_hash' => '1eLJxhw',
    'container.build_id' => '5a085917',
    'container.build_time' => 1775381730,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1eLJxhw');
