<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/api/auth/register']], [], [], []],
    'api_me' => [[], ['_controller' => 'App\\Controller\\AuthController::me'], [], [['text', '/api/me']], [], [], []],
    'api_feed' => [[], ['_controller' => 'App\\Controller\\FeedController::feed'], [], [['text', '/api/feed']], [], [], []],
    'api_post_create' => [[], ['_controller' => 'App\\Controller\\FeedController::createPost'], [], [['text', '/api/posts']], [], [], []],
    'api_post_comment_create' => [['id'], ['_controller' => 'App\\Controller\\FeedController::addComment'], [], [['text', '/comments'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'api_comment_reply_create' => [['id'], ['_controller' => 'App\\Controller\\FeedController::addReply'], [], [['text', '/replies'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/comments']], [], [], []],
    'api_post_like_toggle' => [['id'], ['_controller' => 'App\\Controller\\FeedController::togglePostLike'], [], [['text', '/likes/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'api_comment_like_toggle' => [['id'], ['_controller' => 'App\\Controller\\FeedController::toggleCommentLike'], [], [['text', '/likes/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/comments']], [], [], []],
    'api_post_likes' => [['id'], ['_controller' => 'App\\Controller\\FeedController::postLikes'], [], [['text', '/likes'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'api_comment_likes' => [['id'], ['_controller' => 'App\\Controller\\FeedController::commentLikes'], [], [['text', '/likes'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/comments']], [], [], []],
    'App\Controller\AuthController::register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/api/auth/register']], [], [], []],
    'App\Controller\AuthController::me' => [[], ['_controller' => 'App\\Controller\\AuthController::me'], [], [['text', '/api/me']], [], [], []],
    'App\Controller\FeedController::feed' => [[], ['_controller' => 'App\\Controller\\FeedController::feed'], [], [['text', '/api/feed']], [], [], []],
    'App\Controller\FeedController::createPost' => [[], ['_controller' => 'App\\Controller\\FeedController::createPost'], [], [['text', '/api/posts']], [], [], []],
    'App\Controller\FeedController::addComment' => [['id'], ['_controller' => 'App\\Controller\\FeedController::addComment'], [], [['text', '/comments'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'App\Controller\FeedController::addReply' => [['id'], ['_controller' => 'App\\Controller\\FeedController::addReply'], [], [['text', '/replies'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/comments']], [], [], []],
    'App\Controller\FeedController::togglePostLike' => [['id'], ['_controller' => 'App\\Controller\\FeedController::togglePostLike'], [], [['text', '/likes/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'App\Controller\FeedController::toggleCommentLike' => [['id'], ['_controller' => 'App\\Controller\\FeedController::toggleCommentLike'], [], [['text', '/likes/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/comments']], [], [], []],
    'App\Controller\FeedController::postLikes' => [['id'], ['_controller' => 'App\\Controller\\FeedController::postLikes'], [], [['text', '/likes'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/posts']], [], [], []],
    'App\Controller\FeedController::commentLikes' => [['id'], ['_controller' => 'App\\Controller\\FeedController::commentLikes'], [], [['text', '/likes'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/comments']], [], [], []],
];
