<?php

namespace ContainerUXUMzoH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FeedController' shared autowired service.
     *
     * @return \App\Controller\FeedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FeedController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ApiFormatter.php';

        $container->services['App\\Controller\\FeedController'] = $instance = new \App\Controller\FeedController(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Repository\\PostLikeRepository'] ?? $container->load('getPostLikeRepositoryService')), ($container->privates['App\\Repository\\CommentLikeRepository'] ?? $container->load('getCommentLikeRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Service\\ApiFormatter'] ??= new \App\Service\ApiFormatter()), ($container->privates['validator'] ?? self::getValidatorService($container)), \dirname(__DIR__, 4));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\FeedController', $container));

        return $instance;
    }
}
